# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 200

checkpoint:
  save_interval: 5000
  save_interval_updates: 5000
  keep_interval_updates: 1
  no_epoch_checkpoints: true
  best_checkpoint_metric: wer

task:
  _name: asr_finetuning
  data: ???
  normalize: false
  labels: ltr
  autoregressive: true
  eval_wer: true
  bart_path: ???
  debug: false

dataset:
  num_workers: 6
  max_tokens: 640000
  skip_invalid_size_inputs_valid_test: true
  validate_after_updates: 5000
  validate_interval: 5000
  valid_subset: dev_other

distributed_training:
  ddp_backend: legacy_ddp
  distributed_world_size: 3

criterion:
  _name: cross_entropy

optimization:
  max_update: 50000
  lr: [0.00002]
  sentence_avg: true
  update_freq: [4]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-08

lr_scheduler:
  _name: tri_stage
  phase_ratio: [0.1, 0.4, 0.5]
  final_lr_scale: 0.05

model:
  _name: wav2bart
  w2v_path: ???
  apply_mask: true
  mask_prob: 0.65
  mask_channel_prob: 0.25
  mask_channel_length: 64
  layerdrop: 0.1
  activation_dropout: 0.1
  feature_grad_mult: 0.0
  freeze_finetune_updates: 50000
  bart_path: ???
  fix_encoder: false